version: "3.6"
services:
  rar:
    container_name: rar
    image: asoltys/raretoshi
    ports:
      - "3004:3000"
    restart: always
  lapp:
    depends_on:
      - hasura
      - hbp
      - redis
      # - liquid
    container_name: lapp
    image: gcr.io/coinos-326717/github.com/tokenocean/raretoshi-server:prod
    restart: always
    command: ["pnpm", "dev"]
    environment:
      APP_URL: "${APP_URL}"
      AUTH_EVENT_VALUE: "${AUTH_EVENT_VALUE}"
      CLOUDFLARE_TOKEN: "${CLOUDFLARE_TOKEN}"
      CLOUDFLARE_ZONE: "${CLOUDFLARE_ZONE}"
      COINOS_TOKEN: "${COINOS_TOKEN}"
      COINOS_URL: "${COINOS_URL}"
      DOMAIN: "${DOMAIN}"
      HASURA_JWT: "${HASURA_GRAPHQL_JWT_SECRET}"
      HASURA_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_URL: "${HASURA_URL}"
      HBP_URL: "${HBP_URL}"
      IPFS_URL: "${IPFS_URL}"
      IPFS_WEB_URL: "${IPFS_WEB_URL}"
      LIQUID_ELECTRS_URL: "${LIQUID_ELECTRS_URL}"
      NFT_STORAGE_TOKEN: "${NFT_STORAGE_TOKEN}"
      SERVER_URL: "${SERVER_URL}"
      SIGNING_SERVER_MNEMONIC: "${SIGNING_SERVER_MNEMONIC}"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PASS: "${SMTP_PASS}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_SENDER: "${SMTP_SENDER}"
      SMTP_USER: "${SMTP_USER}"
      RPCHOST: "${RPCHOST}"
      RPCPORT: "${RPCPORT}"
      RPCUSER: "${RPCUSER}"
      RPCPASS: "${RPCPASS}"
      RPCWALLET: "${RPCWALLET}"
    tmpfs:
      - /tmp
    volumes:
      - ./app:/app
      - ./custom:/opt/src/hasura/app/custom
      - ${STORAGE_DIR}:/export
    ports:
      - "8091:8091"
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ${DATA_DIR}:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  hasura:
    container_name: hasura
    image: hasura/graphql-engine:v2.0.9.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_USER}"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_JWT_SECRET: "${HASURA_GRAPHQL_JWT_SECRET}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
  hbp:
    container_name: hbp
    image: nhost/hasura-backend-plus:v2.4.0
    depends_on:
      - hasura
    ports:
      - "3400:3000"
    environment:
      SERVER_URL: "${SERVER_URL}"
      HASURA_ENDPOINT: "${HASURA_URL}/v1/graphql"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      JWT_ALGORITHM: "${JWT_ALGORITHM}"
      JWT_KEY: "${JWT_KEY}"
      AUTO_MIGRATE: "true"
      AUTO_ACTIVATE_NEW_USERS: "true"
      STORAGE_ENABLE: "false"
      MAX_REQUESTS: 10000
      LOST_PASSWORD_ENABLE: "true"
      EMAILS_ENABLE: "true"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USER: "${SMTP_USER}"
      SMTP_PASS: "${SMTP_PASS}"
      SMTP_SENDER: "${SMTP_SENDER}"
      VERIFY_EMAILS: "true"
    volumes:
      - ./app:/app/custom
    restart: always
  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs:v0.14.0
    ports:
      - 8081:8080
      - 4001:4001
      - 5001:5001
    volumes:
      - ${IPFS_DATA}:/data/ipfs
      - ${STORAGE_DIR}:/export
    restart: always
  liquid:
    image: ghcr.io/vulpemventures/elements:0.21.0.2
    container_name: liquid
    volumes:
      - ./liquidmainnet:/home/elements/.elements
    restart: always
  redis:
    container_name: redis
    image: redis
    volumes:
      - ./redis:/data
    restart: always
networks: 
  default: 
    name: net
    external: true
